'use client'

import { useState, useEffect } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ArrowLeft, Music, Calendar, Clock, Globe } from 'lucide-react'
import AudioPlayer from '@/components/audio/AudioPlayer'
import { Track } from '@/types'

export default function TrackDetailPage() {
  const params = useParams()
  const router = useRouter()
  const [track, setTrack] = useState<Track | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    // Mock track data - in production, fetch from API
    const mockTrack: Track = {
      id: params.trackId as string,
      userId: 'user-1',
      title: 'Generated Track',
      genre: 'Rap',
      subGenre: 'Trap',
      language: 'English',
      vibe: 'energetic',
      duration: 30,
      lyrics: 'This is a sample track generated by AI',
      audioUrl: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.wav', // Sample audio URL
      prompt: {
        genre: 'Rap',
        subGenre: 'Trap',
        language: 'English',
        vibe: 'energetic',
        duration: 30,
        lyricsPrompt: 'Create an energetic rap track',
        additionalPrompts: ['Include trap beats', 'Add vocal harmonies']
      },
      metadata: {
        title: 'Generated Track',
        bpm: 140,
        key: 'C minor',
        generatedAt: new Date().toISOString()
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }

    setTimeout(() => {
      setTrack(mockTrack)
      setLoading(false)
    }, 1000)
  }, [params.trackId])

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    )
  }

  if (!track) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 flex items-center justify-center">
        <Card className="max-w-md">
          <CardContent className="p-6 text-center">
            <h2 className="text-xl font-semibold mb-2">Track Not Found</h2>
            <p className="text-muted-foreground mb-4">
              The track you're looking for doesn't exist or you don't have access to it.
            </p>
            <Button onClick={() => router.push('/')}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => router.push('/')}
              >
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back
              </Button>
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                  <Music className="h-5 w-5 text-white" />
                </div>
                <h1 className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                  Musical AI
                </h1>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto space-y-8">
          {/* Track Info */}
          <Card>
            <CardHeader>
              <CardTitle className="text-2xl">{track.title}</CardTitle>
              <div className="flex flex-wrap gap-2 mt-2">
                <Badge variant="secondary">{track.genre}</Badge>
                {track.subGenre && <Badge variant="outline">{track.subGenre}</Badge>}
                <Badge variant="outline">{track.language}</Badge>
                <Badge variant="outline">{track.vibe}</Badge>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="flex items-center space-x-2">
                  <Clock className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Duration:</span>
                  <span className="font-medium">{track.duration}s</span>
                </div>
                <div className="flex items-center space-x-2">
                  <Globe className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Language:</span>
                  <span className="font-medium">{track.language}</span>
                </div>
                <div className="flex items-center space-x-2">
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Created:</span>
                  <span className="font-medium">
                    {new Date(track.createdAt).toLocaleDateString()}
                  </span>
                </div>
              </div>

              {track.lyrics && (
                <div>
                  <h3 className="font-medium mb-2">Lyrics Theme</h3>
                  <p className="text-sm text-muted-foreground">{track.lyrics}</p>
                </div>
              )}

              {track.metadata && (
                <div>
                  <h3 className="font-medium mb-2">Track Details</h3>
                  <div className="grid grid-cols-2 gap-2 text-sm">
                    {track.metadata.bpm && (
                      <div>
                        <span className="text-muted-foreground">BPM:</span> {track.metadata.bpm}
                      </div>
                    )}
                    {track.metadata.key && (
                      <div>
                        <span className="text-muted-foreground">Key:</span> {track.metadata.key}
                      </div>
                    )}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Audio Player */}
          <AudioPlayer
            audioUrl={track.audioUrl}
            title={track.title}
            trackId={track.id}
          />

          {/* Generation Details */}
          <Card>
            <CardHeader>
              <CardTitle>Generation Details</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <div>
                  <h4 className="font-medium mb-1">Original Prompt</h4>
                  <p className="text-sm text-muted-foreground">
                    {track.prompt.lyricsPrompt}
                  </p>
                </div>
                
                {track.prompt.additionalPrompts.length > 0 && (
                  <div>
                    <h4 className="font-medium mb-1">Additional Requirements</h4>
                    <div className="flex flex-wrap gap-1">
                      {track.prompt.additionalPrompts.map((prompt, index) => (
                        <Badge key={index} variant="outline" className="text-xs">
                          {prompt}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
